/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require('express');
const bodyParser = require('body-parser');
const fs = require('node:fs').promises;

const app = express();

app.use(bodyParser.json());

let id = 1;

async function parseJson(filepath) {
     try {
        const data = await fs.readFile(filepath, 'utf-8');
        return JSON.parse(data);
    } catch {
        return [];
    }
}

async function storeTodo(filepath, todos) {
    await fs.writeFile(filepath, JSON.stringify(todos), 'utf-8');
}

app.get('/todos', async (req, res) => {
   
    const todos = await parseJson('./todos.json');

    res.statusCode = 200;
    
    res.json(todos);
})

app.get('/todos/:id', async (req, res) =>{
    const {id} = req.params;
    const todos = await parseJson('./todos.json');

    const todo  = todos.find(t => t.id === Number(id));

    if(!todo) {
        return res.status(404).json({message: 'Not found'});
    }

    return res.status(200).json(todo);
})

app.post('/todos', async (req, res) => {
    const todo =  req.body;
    todo.id = id++;

    const todos = await parseJson('./todos.json');

    todos.push(todo);
    console.log(todo)
    await storeTodo('./todos.json', todos);

    return res.status(201).json({id: todo.id});

})

app.put('/todos/:id', async (req, res) => {
    const {title, completed} =  req.body;
    const requiredId = req.params.id;

    const todos = await parseJson('./todos.json');
    
    const idx = todos.findIndex(t => t.id === Number(requiredId));

    if(idx === -1) {
        return res.status(404).json({message: 'not found'});
    }

    todos[idx].title = title;
    todos[idx].completed = completed;
    await storeTodo('./todos.json', todos);

    return res.status(200).json({todos});
})

app.delete('/todos/:id', async (req, res) => {
    const requiredId = req.params.id;

    const todos = await parseJson('./todos.json');
    
    const idx = todos.findIndex(t => t.id === Number(requiredId));

    if(idx === -1) {
        return res.status(404).json({message: 'not found'});
    }

    todos.splice(idx, 1);
    await storeTodo('./todos.json', todos);
    return res.status(200).json({todos});
})

app.use((req,res)=>{
  res.status(404).json({message:"Route not found"});
});


module.exports = app;


// const express = require('express');
// const bodyParser = require('body-parser');
// const fs = require('node:fs').promises;

// const app = express();
// app.use(bodyParser.json());

// let id = 1;
// const FILE = './todos.json';

// async function parseJson() {
//     try {
//         const data = await fs.readFile(FILE, 'utf-8');
//         return JSON.parse(data);
//     } catch {
//         return [];
//     }
// }

// async function storeTodo(todos) {
//     await fs.writeFile(FILE, JSON.stringify(todos), 'utf-8');
// }

// app.get('/todos', async (req, res) => {
//     const todos = await parseJson();
//     res.status(200).json(todos);
// });

// app.get('/todos/:id', async (req, res) => {
//     const todos = await parseJson();
//     const todo = todos.find(t => t.id === Number(req.params.id));

//     if (!todo) {
//         return res.status(404).json({ message: "Not found" });
//     }

//     res.status(200).json(todo);
// });

// app.post('/todos', async (req, res) => {
//     const todos = await parseJson();

//     const todo = {
//         id: id++,
//         title: req.body.title,
//         description: req.body.description,
//         completed: req.body.completed ?? false
//     };

//     todos.push(todo);
//     await storeTodo(todos);

//     res.status(201).json({ id: todo.id });
// });

// app.put('/todos/:id', async (req, res) => {
//     const todos = await parseJson();
//     const idx = todos.findIndex(t => t.id === Number(req.params.id));

//     if (idx === -1) {
//         return res.status(404).json({ message: "Not found" });
//     }

//     todos[idx] = { ...todos[idx], ...req.body };

//     await storeTodo(todos);

//     res.status(200).json(todos[idx]);
// });

// app.delete('/todos/:id', async (req, res) => {
//     const todos = await parseJson();
//     const idx = todos.findIndex(t => t.id === Number(req.params.id));

//     if (idx === -1) {
//         return res.status(404).json({ message: "Not found" });
//     }

//     todos.splice(idx, 1);

//     await storeTodo(todos);

//     res.status(200).json({ message: "Deleted" });
// });

// app.use((req, res) => {
//     res.status(404).json({ message: "Route not found" });
// });

// module.exports = app;

